name: Publish docker image
on:
  push:
    branches: [ master ]
  release:
    types:
      - published
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Push Docker image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: helibdocker/helloworld_repo:latest

